name: Compile and run Roblox tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  
  compile:
    name: Set up NPM
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Install NodeJS
        uses: actions/setup-node@master
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
      - name: Install node_modules
        run: |
          npm install -g roblox-ts@latest
          npm install
          
      - run: cd ..
      
      - name: where am I?
        run: pwd
      
      - name: what files?
        run: ls
      
      - name: Compile
        run: rbxtsc build
    
      
  test:
    name: TestEZ
    runs-on: windows-latest
    
    needs: compile
    
    steps:
      - uses: actions/checkout@v2
