name: Compile then run Roblox tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  compile-and-test:
    name: Compile to Luau then run TestEZ through run-in-roblox
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install NPM packages
        run: npm ci
      
      - name: Install Foreman packages
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.0
        with:
          cookie: ${{ secrets.ROBLOSECURITY }}
          token: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 2

      - name: Compile TS to Luau
        run: npx rbxtsc --verbose --project=./ --rojo=./default.project.json

      - name: Build place file (rbxlx)
        run: rojo build default.project.json --output testGame.rbxlx
        
      - name: Build place file (rbxl)
        run: rojo build default.project.jsosn --output testGame.rbxl
       
      - run: dir /o:-sn
       
      - name: Run TestEZ tests
        run: run-in-roblox --place testGame.rbxlx --script spec.lua
