name: Compile then run Roblox tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  compile-and-test:
    name: Compile to Luau then run TestEZ through run-in-roblox
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Node
        uses: actions/setup-node@master
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install NPM packages
        run: |
          npm ci
          npm install --global --production roblox-ts@latest
          
      - name: Compile TS to Luau
        run: rbxtsc --verbose --project=./ --rojo=./default.project.json
      
      - name: Install Foreman packages
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build place file
        run: rojo build -o ./testPlace.rbxlx
