name: Compile and run Roblox tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  
  npm-stuff:
    name: Set up NPM
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - run: npm ci
      
  compile:
    name: Compile TS to Luau
    runs-on: ubuntu-latest
    
    needs: npm-stuff
    
    steps:
      - uses: actions/checkout@v2
      - run: rbxtsc build
      
  test:
    name: TestEZ
    runs-on: windows-latest
    
    needs: compile
    
    steps:
      - uses: actions/checkout@v2
