name: Compile and run Roblox tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  compile-and-test:
    name: Set up NPM
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Node
        uses: actions/setup-node@master
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install NPM packages
        run: |
          npm ci
          npm install -g roblox-ts@latest
          
      - name: Compile TS to Luau
        run: rbxtsc --verbose --project=./ --rojo=./default.project.json
      
      - run: Get-Item .\*
